# Generated by Django 5.2.8 on 2025-12-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeamApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Draft', 'Draft'), ('Public', 'Public'), ('Closed', 'Closed')], default='Draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagID', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('ShortDescription', models.TextField()),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('VotesCount', models.IntegerField(default=0)),
                ('IdeaID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaApp.category')),
                ('CreaterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamApp.team')),
                ('StatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IdeaApp.status')),
                ('Tags', models.ManyToManyField(to='IdeaApp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('MediaID', models.AutoField(primary_key=True, serialize=False)),
                ('MediaPath', models.FileField(upload_to='media/')),
                ('MediaType', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Document', 'Document')], max_length=20)),
                ('IdeaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdeaApp.idea')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='IdeaApp.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='UserApp.user')),
            ],
        ),
    ]
