# Generated by Django 6.0 on 2025-12-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaApp', '0001_initial'),
        ('TeamApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='TeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamApp.team'),
        ),
    ]
