# Generated by Django 5.2.8 on 2025-12-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Partipicant'), (3, 'Team Leader'), (4, 'Judge')], default=2, verbose_name='User Role')),
            ],
        ),
    ]
